### ISSUE TITLE
Having issues with people bullying me on IRC

### ISSUE THREAD

**Issue by detonation** [MaverickEsq/stop-irc-bullying#1]
I'm in a channel devoted as a fanclub to a certain user, and I seem to get a lot of bullying from marsupials and a certain Pilosa. Any help would be appreciated in stopping this targeted, albeit slow, harassment

**Comment by MaverickEsq** [comment]
Hi detonation, I'm sorry to hear you've been getting bullied, however this is an area for technical support of the website software. If you need support handling bullying you can check out the foundation's Best Practices page https://stop-irc-bullying.info/best-practice or get contact information on the Live Chat page https://stop-irc-bullying.info/live-chat

**Comment by detonation** [comment]
Thank you for the correction. I am new to this site and was unaware of the proper route to take. I apologize for incorrect usage. Thank you again
